### ISSUE TITLE
How about a plot of the history of the epochs in the fit?

### ISSUE THREAD

**Issue by mjg4243** [rdrr1990/kerasformula#2]
Would be handy for me, at least.  I did check the contents of the kms function and there is a lot of good stuff -- but nothing of the history I can see.  Thanks for giving this a look

**Comment by rdrr1990** [comment]
Thanks for bringing this issue up! You can plot the history this way:

```
out <- kms(some_outcome ~ ., some_data)
plot(out$history)
```
One thing that `keras` does that's very nice for bigger models is plot by epoch-by-epoch as the model fits, which is perhaps what you are referring to. I plan to add that in.

**Comment by mjg4243** [comment]
Thanks for responding so promptly.  I hadn't noticed the history file in the output --
And the graph is what I was thinking of.
Best regards Mike Gallagher

**Comment by rdrr1990** [comment]
Great!
