### ISSUE TITLE
Possible to make "data" 1st argument?

### ISSUE THREAD

**Issue by eoppe1022** [rdrr1990/kerasformula#8]
Hey, awesome package. Do you think it would be possible to rearrange the formula so that `data` is the first argument? That way, the formula could be pipeable like `data %>% kms()`

**Comment by rdrr1990** [comment]
Thanks! Sorry for delayed reply--caught me traveling. I made the formula the first argument so as to make the function feel like 'lm' or 'glm'. However you can pipe data like so:

```
iris %>% 
    kms(input_formula = "Species ~ .") 
       %>% plot_confusion
```
or 
```
mtcars %>% 
   filter(complete.cases(mpg)) %>% 
     kms(input_formula = "mpg ~.") ->
out
```
How's that seem?

(Also added more permanent example [here](https://github.com/rdrr1990/kerasformula/blob/master/examples/piping.md))

**Comment by eoppe1022** [comment]
That's awesome! Nice work. Feel free to close if you want.

**Comment by rdrr1990** [comment]
Great!
